### PR TITLE
SphereRenderer: Renaming and Compatibility

### PR DESCRIPTION
**Pull request by braunms**
- Renamed **SimpleSphereRenderer** to **SphereRenderer**
- Renamed render modes 
- Renamed shaders
- Extended OpenGL backward compatibility of SIMPLE render mode.
- Extended OpenGl compatibility checks
- Removed render mode toggle parameter

### CODE REVIEW

**Comment by gralkapk** [comment]
These lines of code
https://github.com/UniStuttgart-VISUS/megamol-dev/blob/3989495f56fe610724700caad36427f9521384f0/core/include/mmcore/moldyn/SphereRenderer.h#L131-L135
prevent it from running on headless cluster nodes, etc.

**Comment by gralkapk** [comment]
Testspheres scripts need a GUIView

**Comment by braunms** [comment]
There is already a separate example project containing the GUIView.
In commit f8c3c23 the **project_files/testspheres_gui.lua** was adopted to use the new GUIView.

**Comment by gralkapk** [comment]
Well, we don't need sample projects that don't have a GUI, do we?

**Review by tobiasrau — CHANGES_REQUESTED** [review]
This pull request recommits already deleted files (by #329).

**Review by tobiasrau — APPROVED** [review]

**Pull request merged**
