### PR TITLE
Coding day 0819 PR

### PR DESCRIPTION
**Pull request by tobiasrau**
Collection of commits that contain changes to fit renderer modules for the new camera.

### CODE REVIEW

**Comment by tobiasrau** [comment]
Contains suggested implementation of and resolves #417 .

**Comment by gralkapk** [comment]
Resolves #427 and resolves #428 and resolves #429.
Some issues in #431

**Comment by tobiasrau** [comment]
Resolves #430.

**Comment by straubar** [comment]
Resolves #415

**Comment by tobiasrau** [comment]
Also resolves #424, resolves #425, resolves #432, resolves #419, resolves #421, resolves #433, resolves #434 and resolves #435.

**Review by straubar — CHANGES_REQUESTED** [review]
@invor 
In 'core/Shaders/dfr/lambert_fragment.glsl':
- [ ] 'vec3 depthToWorldPos(float depth, vec2 uv)' returns view space position instead of world space, having two return statements on the same path.
- [ ] in 'void main(void)', the Lambert function is called in wrong parameter order.

@braunms 
In 'plugins/cinematic/src/CallKeyframeKeeper.h':
In 'plugins/cinematic/src/KeyframeKeeper.h':
In 'plugins/cinematic/src/KeyframeManipulator.h':
- [x] why do you still use vislib::Array instead of the equivalent from the STL?

**Comment by geringsj** [comment]
resolves #422

**Comment by braunms** [comment]
Bei mir kommt unter Linux der Fehler: 
error: make[2]: *** No rule to make target 'core/libpng_ext-prefix/lib64/libpng16.a', needed by 'core/libcore.so'.  Stop.

**Comment by braunms** [comment]
The merge conflicts with the master for the files
core/Shaders/arrow.btf
core/include/mmcore/moldyn/SphereRenderer.h
core/src/moldyn/SphereRenderer.cpp
plugins/mmstd_moldyn/src/mmstd_moldyn.cpp 
should be easy to resolve by taking only the version in the cd brach. 
All fixes and changes of this files merged into the master are also done in the cd-brach.

**Comment by invor** [comment]
resolves #421 and #425, partly resolves #420

**Review by gralkapk — APPROVED** [review]

**Review by straubar — APPROVED** [review]

**Pull request merged**
